@startuml UC2_Containers

top to bottom direction

'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
!include <C4/C4_Container.puml>

Person(user, "Пользователь", "Клиент банка")

Container_Boundary(app, "Интернет-банк") {
    Container(webapp, "Веб-клиент")
    Container(gateway, "API Gateway", "Маршрутизация запросов")
    Container(monolith, "Монолит", "ASP.NET MVC 4.5")
    ContainerDb(monolith_db, "App Db", "MS SQL")
    Container(deposit, "Сервис депозитов", "ASP.NET MVC 4.5")
    ContainerDb(deposit_db, "Deposit Db", "MS SQL")
    Container(broker, "Брокер сообщений", "Kafka")
}

Container_Boundary(bank, "Банковская система") {
    Container(abs, "АБС", "Delphi")
    Container(sms, "СМС-шлюз", "")
    ContainerDb(db, "ABS Db", "Oracle")
}

System_Ext(provider, "Провайдер")

Rel(user, webapp, "Формирование заявки/ подтверждение операции")
Rel(webapp, gateway, "Передача запроса")
Rel(gateway, deposit, "Операции по депозитам")
Rel(gateway, monolith, "Прочие операции")
Rel(deposit, deposit_db, "")
Rel(monolith, monolith_db, "")
Rel(deposit, broker, "Запрос к АБС")
Rel(monolith, broker, "Запрос к АБС")
Rel(broker, abs, "Сообщения клиента")

Rel_R(abs, sms, "Код подтверждения")
Rel(abs, db, "Хранение данных")
Rel(sms, provider, "Код подтверждения")

Rel(provider, user, "Код подтверждения")

@enduml